defaults: &defaults
  host: localhost
  # This needs to be here... any way to get rid of this?
  adapter: sqlite3

development:
  <<: *defaults
  database: db/riggifier.sqlite3
  
production:
  <<: *defaults
  database: db/riggifier.sqlite3