defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: riggifier
  
production:
  <<: *defaults
  database: riggifier
  
test:
  <<: *defaults
  database: riggifier_test
  
integration:
  <<: *defaults
  database: riggifier_integration