login: &login
  user: root
  adapter: postgresql

development:
  <<: *login
  database: hardwarepedia_development
  pool: 25
  # timeout: 5000

production:
  <<: *login
  database: hardwarepedia_production
  pool: 25
  # timeout: 5000

test:
  <<: *login
  database: hardwarepedia_test
