defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: hardwarepedia_development
  
production:
  <<: *defaults
  database: hardwarepedia_production

test:
  <<: *defaults
  database: hardwarepedia_test