defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: hardwarepedia_development
  
development:
  <<: *defaults
  database: hardwarepedia_development

test:
  <<: *defaults
  database: hardwarepedia_test

# set these environment variables on your prod server
#production:
#  <<: *defaults
#  database: hardwarepedia
#  username: <%= ENV['MONGO_USERNAME'] %>
#  password: <%= ENV['MONGO_PASSWORD'] %>
